<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Trimlet.Media\Trimlet.Media.csproj" />
    <ProjectReference Include="..\..\src\Trimlet.Platform.Windows\Trimlet.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
